name: build and test feature branch
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Pull and checkout from git repository
        run: echo "pulling and checking out from git repository"

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: .
        shell: bash
        run: |
          chmod +x mvnw || true
          ./mvnw clean test package
